### ISSUE TITLE
matrix view mode

### ISSUE THREAD

**Issue by Be-ing** [MrBollie/bbfpromix#2]
I have looked at some of RME's resources about TotalMix FX and I understand how this program is designed now. However, the complexity is *way* overkill for what I need and takes some explanation. All I need is a routing matrix, which is obvious how to use. I can't think of a use case in which I would want to have anything other than unity or negative infinity gain for any routing. This way I only need to control the levels of the hardware inputs and outputs. TotalMix FX has an alternate view mode like this. From https://www.rme-usa.com/totalmix-fx.html
![image](https://www.rme-usa.com/files/uploads/Content-Bilder/matrix-view.jpg)
> TotalMix FX has 2 different view modes, the mixer, which is default, and a matrix view. You can switch between the modes in the Function menu at the top of the screen or window. Alternately, you can hit the X key on your keyboard for the Matrix, and M key to switch back to Mixer view.

**Comment by MrBollie** [comment]
This is indeed a nice feature, but I don't really have time to implement it. But if anyone feels inclined to do so, I look forward to a pull request. :)
