### ISSUE TITLE
synchronize state with hardware

### ISSUE THREAD

**Issue by Be-ing** [MrBollie/bbfpromix#4]
Currently when this application is opened, it does not read the state of the mixer from the hardware. I am not sure if this is a limitation of the kernel, this application, or both. Ideally there should be full duplex synchronization so I could change a setting on the hardware and see it reflected on screen and vice versa.

**Comment by Be-ing** [comment]
It looks like there is [code to do this](https://github.com/MrBollie/bbfpromix/blob/master/src/channel.c#L356), so I presume this is a limitation of the kernel?

**Comment by MrBollie** [comment]
Like I wrote on the issue you filed with the patch itself: There's currently no known USB control request to read any state from the hardware.
